# Generated by Django 5.2.4 on 2026-03-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analyzedclause',
            name='simplified_malayalam',
        ),
        migrations.AddField(
            model_name='analyzedclause',
            name='ai_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
