# Generated by Django 5.2.4 on 2026-03-22 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0002_remove_analyzedclause_simplified_malayalam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LawSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='analysis_app.lawresource')),
            ],
        ),
    ]
