# Generated by Django 5.2.4 on 2026-03-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_app', '0003_lawresource_lawsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedclause',
            name='ai_rewritten_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
